spring:
  application:
    name: atomik-api
  profiles:
    default: dev

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/atomik_db}
    username: ${DB_USERNAME:atomik_user}
    password: ${DB_PASSWORD:atomik_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate  # O Hibernate apenas valida o banco (Segurança)
    open-in-view: false   # Melhora a performance desativando o OSIV (Padrão Pleno)

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    enabled: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

# Configuração do Swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  pattern:
    level: "%5p [rid:%X{requestId:-na}]"

api:
  security:
    token:
      secret: ${JWT_SECRET:change-me-in-dev}
