spring:
  application:
    name: atomik-api
  
  datasource:
    url: jdbc:postgresql://localhost:5432/atomik_db
    username: atomik_user
    password: atomik_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate  # O Hibernate apenas valida o banco (Segurança)
    show-sql: true        # Mostra o SQL no console
    open-in-view: false   # Melhora a performance desativando o OSIV (Padrão Pleno)
    properties:
      "[hibernate.format_sql]": true
      "[hibernate.highlight_sql]": true # Deixa o SQL colorido no terminal

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

  data:
    redis:
      host: localhost
      port: 6379

# Configuração do Swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html